- name: Setup EC2 Instance
  hosts: ec2
  become: yes
  tasks:
    - name: Update repositories
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install Minikube dependencies
      apt:
        name: conntrack
        state: present
        update_cache: yes

    - name: Download Minikube
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: Start Minikube
      shell: minikube start --driver=none
      become_user: ubuntu